### ISSUE TITLE
Crashes And  Recognized

### ISSUE THREAD

**Issue by sjustfly** [glmcdona/binary2strings#17] opened 2023-07-12 00:50 UTC
My parameter settings are min_chars = 4 and only_interesting = false.

There are two issues.

 First, when I input a binary string of 0000000000, it crashes on "proba_interesting_avg = proba_interesting_avg_vect[i];".

 Second, when I set the buffer very short, such as "ok" which only has 2 characters, it cannot be recognized.

**Comment by glmcdona** [comment] 2023-07-12 04:30
Thanks for the report @sjustfly.

> binary string of 0000000000

I just added a bunch more extensive unit tests:
https://github.com/glmcdona/binary2strings/blob/main/tests/test.py

This test included strings with just five null values like shown. I found no issue locally, and looking at the referenced line of code, I can't figure out how an error could occur on that line. By any chance do you have some python code, or a binary file paired with python code that can repro the issue? Which OS are you using?

> when I set the buffer very short, such as "ok" which only has 2 characters, it cannot be recognized.

That is the default behaviour by design. `min_chars` parameter controls the minimum length of the string it's willing to extract as a valid string. This defaults to 4 to reduce noise when extracting strings, but can be overridden. If you'd like to extract strings of length 1 or 2 characters as well, set `min_chars` = 1. I added unit tests that validate this is working as expected. Hope this helps!

**Comment by sjustfly** [comment] 2023-07-12 05:18
I used C++ code that I downloaded and compiled directly from the file. The method I used is "vector<std::tuple<string, string, std::pair<size_t, size_t>, bool>> extract_all_strings(const unsigned char buffer[], size_t buffer_size, size_t min_chars, bool only_interesting)". I did the recognition by reading the file as binary. I have uploaded two files to GitHub, you can download and try them.

// The file that causes a crash
https://github.com/sjustfly/file_storate/blob/main/crash

// The file that cannot be recognized, containing only the string "ok"; setting min_chars to 1 does not work.
https://github.com/sjustfly/file_storate/blob/main/ok

**Comment by glmcdona** [comment] 2023-07-13 04:25
Those two test files work correctly on my local testing through the python interface. Do you have the code you are using to repro it?

**Comment by sjustfly** [comment] 2023-07-14 12:28
https://github.com/sjustfly/file_storate/blob/main/BinaryToString.zip

I tried again and found that short characters can be recognized, but the crashing issue still exists. I have put the file and demo in this compressed file.

**Comment by glmcdona** [comment] 2023-07-15 03:27
Thanks for sharing. I had a look at the code you submitted, and the problem looks to be you've modified the code of the `extract_all_strings()` function which introduced some issues.

> First, when I input a binary string of 0000000000, it crashes on "proba_interesting_avg = proba_interesting_avg_vect[i];".

You've added code which in the case of a failed string extraction at a position, it will add a hex encoded character as a string option as well. This introduces this bug because the `r_vect` array needs to be exactly the same length as `proba_interesting_vect` and `proba_interesting_avg_vect` causing this exception. I might recommend removing the interesting string logic from the code if you are going to use it this way.

> Second, when I set the buffer very short, such as "ok" which only has 2 characters, it cannot be recognized.

Nothing jumps out at me as the problem here other than the min_chars needs to be changed from 4 to 2 or smaller. I imagine you already tried that. Maybe your modification or other modifications caused it to not work somehow? This is working in all the unit tests for the library.

**Comment by glmcdona** [comment] 2023-07-15 03:28
Closing the issue since I think it's related to the altered code. Happy to continue discussing though.

**Closed as not planned by glmcdona** 2023-07-15 03:28 UTC
